use_frameworks!

platform :ios, '8.0'

target 'SKSugarOC_Example' do
  pod 'SKSugarOC', :path => '../'

  target 'SKSugarOC_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
