# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SKSugarOCExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SKSugarOCExample
  
  pod 'SKSugarOC'
  
  
  

  target 'SKSugarOCExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SKSugarOCExampleUITests' do
    # Pods for testing
  end

end
